services:
  mysql-db:
    image: mysql:latest
    container_name: igaming-platform-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: igaming_platform_db
    ports:
      - "3307:3306"
    volumes:
      - igaming_platform_db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: igaming-platform-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  igaming_platform_db_data:
