definitions:
  common.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  common.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  description: API for managing players, tournaments and prizes.
  title: iGaming Platform API
  version: "1.0"
paths:
  /tournaments/{id}/distribute:
    post:
      description: Distribute prizes based on tournament ranking
      parameters:
      - description: Tournament ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Prizes successfully distributed
          schema:
            allOf:
            - $ref: '#/definitions/common.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Distribute prizes
      tags:
      - Tournaments
swagger: "2.0"
