definitions:
  common.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  common.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  player.PlayerRanking:
    properties:
      account_balance:
        type: number
      id:
        type: integer
      name:
        type: string
      player_rank:
        type: integer
    type: object
info:
  contact: {}
  description: API for managing players, tournaments and prizes.
  title: iGaming Platform API
  version: "1.0"
paths:
  /players/ranking:
    get:
      description: Retrieve a ranking list of all players based on their account balances.
      responses:
        "200":
          description: Player ranking fetched successfully
          schema:
            allOf:
            - $ref: '#/definitions/common.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/player.PlayerRanking'
                  type: array
              type: object
        "500":
          description: Failed to fetch player ranking
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get global player ranking
      tags:
      - Players
  /tournaments/{id}/distribute:
    post:
      description: Distribute prizes based on tournament ranking
      parameters:
      - description: Tournament ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Prizes successfully distributed
          schema:
            allOf:
            - $ref: '#/definitions/common.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Distribute prizes
      tags:
      - Tournaments
swagger: "2.0"
